# -*- coding: utf-8 -*-
"""APP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mmVltiEtQ5Zcb0sXSi07qtwlRNxTAyWR
"""

# Commented out IPython magic to ensure Python compatibility.
# import the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline

import pyspark
from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark import SparkContext, SparkConf

spark = SparkSession.builder \
    .master("local[1]") \
    .appName("ClusteringApp") \
    .config("spark.driver.memory", "8g") \
    .config("spark.executor.memory", "8g") \
    .config("spark.sql.shuffle.partitions", "200") \
    .getOrCreate()

!pip install streamlit pyngrok

from pyspark.ml import Pipeline
from pyspark.ml.feature import RegexTokenizer, NGram, HashingTF, MinHashLSH, StopWordsRemover
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, regexp_replace, trim
import pandas as pd

# Initialize Spark session
spark = SparkSession.builder.master("local[1]").appName("ClusteringApp").getOrCreate()

# Load and clean dataset
def load_and_clean_data():
    csv_path = "/content/headlines.csv"  # Make sure this path is correct in your setup
    df = pd.read_csv(csv_path, encoding="utf-8")
    df = df.rename(columns={"headline": "text", "newspaper name": "newspaper_name"})
    df_filtered = df[df["category"].isin(["sports", "International", "politics"])]

    df_sports = df_filtered[df_filtered["category"] == "sports"].head(5000)
    df_international = df_filtered[df_filtered["category"] == "International"].head(5000)
    df_politics = df_filtered[df_filtered["category"] == "politics"].head(5000)

    final_df = pd.concat([df_sports, df_international, df_politics], ignore_index=True)
    final_df["doc_id"] = final_df.index + 1
    final_df = final_df[["doc_id", "text", "category", "newspaper_name"]]
    final_df = final_df.head(220)  # Limit to 230 rows
    final_df["joined"] = final_df["text"]  # Added "joined" column for n-grams
    return final_df

# Preprocessing pipeline
def build_pipeline():
    tokenizer = RegexTokenizer(inputCol="text", outputCol="tokens")
    bn_stop = [
        "এ", "এই", "ওই", "সে", "তাঁর", "তাদের", "এরা", "ওরা", "যে", "যা", "যার", "যদি", "যদিও",
        "এবং", "কিন্তু", "তবে", "অথবা", "অথচ", "তাই", "তাহলে", "তাতে",
        "আমি", "আমরা", "তুমি", "আপনি", "আপনার", "তোমার", "সে", "তিনি", "তারা",
        "কি", "কেন", "কবে", "কোথায়", "কিভাবে",
        "হয়", "হবে", "হয়েছে", "ছিল", "ছিলেন", "থাকে", "থাকবে", "থাকতে",
        "নয়", "না", "তো", "টি", "টা", "গুলো", "গুলি", "আর", "ও", "এর", "কে", "কো",
        "একটা", "একটি", "কিছু", "সব", "সবাই", "কোনো", "কোন", "প্রতি", "প্রায়",
        # add/remove to taste
    ]
    remover = StopWordsRemover(inputCol="tokens", outputCol="tokens_clean", stopWords=bn_stop)
    ngrams = NGram(n=2, inputCol="tokens_clean", outputCol="shingles")
    hasher = HashingTF(inputCol="shingles", outputCol="features", numFeatures=(1 << 10), binary=True)
    mh = MinHashLSH(inputCol="features", outputCol="lsh", numHashTables=8)

    pipeline = Pipeline(stages=[tokenizer, remover, ngrams, hasher, mh])
    return pipeline

# Load data and preprocess
df_clean = load_and_clean_data()

# Convert to Spark DataFrame
df_clean_spark = spark.createDataFrame(df_clean)

# Build and fit the pipeline
pipeline = build_pipeline()
model_bangla = pipeline.fit(df_clean_spark)

# Apply the model to the data
feats_bangla = model_bangla.transform(df_clean_spark)

# Save the fitted model for later use
model_bangla.save("/content/bangla_model")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile appUp.py
# import streamlit as st
# import pandas as pd
# import matplotlib.pyplot as plt
# import seaborn as sns
# from pyspark.sql import SparkSession
# from pyspark.ml.feature import RegexTokenizer
# from pyspark.ml import PipelineModel
# from pyspark.sql.functions import col, lit
# from pyspark.sql.functions import size, explode, trim, length, lower
# from pyspark.sql.types import ArrayType, StringType
# from pyspark.ml.evaluation import ClusteringEvaluator
# import plotly.express as px
# from wordcloud import WordCloud
# import matplotlib.font_manager as fm
# import os
# from pyspark.ml.feature import NGram
# from pyspark.sql import functions as F
# from pyspark.sql.functions import explode, desc, size, col, trim, lower
# from sklearn.feature_extraction.text import CountVectorizer
# 
# # ===================== Spark & Model =====================
# spark = SparkSession.builder.master("local[1]").appName("ClusteringApp").getOrCreate()
# model_bangla = PipelineModel.load("/content/bangla_model")
# 
# # ===================== Sample Queries =====================
# sample_queries = [
#     ("1001", "নাইজেরিয়াকে সমতায় ফেরালেন মোজেস"),
#     ("1002", "সমতায় শেষ জাপানসেনেগালের প্রথমার্ধ "),
#     ("1003", "স্টোনসের গোলে এগিয়ে গেল ইংল্যান্ড"),
#     ("1004", "ওজিলকে নিয়ে ভীষণ চাপে জার্মানি"),
#     ("1005", "নেইমারের গোলে হাত ভাঙল বোনের"),
#     ("1006", "হ্যাজার্ডের গোলে এগিয়ে গেল বেলজিয়াম"),
#     ("1007", "এবার আর্জেন্টিনাকে হারিয়ে দিল ভারত"),
#     ("1008", "এরদোগান ইস্যু উড়িয়ে ওজিলকে নিয়ে মাঠে জার্মানি")
# ]
# query_data = spark.createDataFrame(sample_queries, ["doc_id", "text"])
# query_feats = model_bangla.transform(query_data)
# 
# # ===================== Data Loader =====================
# def load_and_clean_data():
#     csv_path = "/content/headlines.csv"
#     df = pd.read_csv(csv_path, encoding="utf-8")
#     df = df.rename(columns={"headline": "text", "newspaper name": "newspaper_name"})
#     df_filtered = df[df["category"].isin(["sports", "International", "politics"])]
#     df_sports = df_filtered[df_filtered["category"] == "sports"].head(5000)
#     df_international = df_filtered[df_filtered["category"] == "International"].head(5000)
#     df_politics = df_filtered[df_filtered["category"] == "politics"].head(5000)
#     final_df = pd.concat([df_sports, df_international, df_politics], ignore_index=True)
#     final_df["doc_id"] = final_df.index + 1
#     final_df = final_df[["doc_id", "text", "category", "newspaper_name"]]
#     final_df = final_df.head(220)
#     return final_df
# 
# df_clean = load_and_clean_data()
# df_clean_spark = spark.createDataFrame(df_clean)
# feats_bangla = model_bangla.transform(df_clean_spark).select("doc_id", "text", "features")
# 
# # ===================== Nearest Neighbors =====================
# def find_neighbors(query_row):
#     query_features = query_row["features"]
#     mh_model = model_bangla.stages[-1]
#     nn = mh_model.approxNearestNeighbors(feats_bangla, query_features, numNearestNeighbors=5, distCol="distCol")
#     nn_with_similarity = (
#         nn.withColumn("jaccard_similarity", lit(1.0) - col("distCol"))
#           .select("doc_id", "text", "jaccard_similarity")
#           .orderBy(col("jaccard_similarity").desc())
#     )
#     return nn_with_similarity
# 
# # ===================== Clustering Loader =====================
# @st.cache_data
# def load_clustered_data(k_value):
#     csv_path = f'clustered_data_k{k_value}.csv'
#     df_clustered = pd.read_csv(csv_path)
#     return df_clustered
# 
# # ===================== Plot Functions =====================
# def plot_token_count_distribution(spark_df):
#     tokenizer = RegexTokenizer(inputCol="text", outputCol="tokens")
#     tokenized_df = tokenizer.transform(spark_df)
#     length_df = tokenized_df.withColumn("token_count", size("tokens"))
#     length_pd = length_df.select("doc_id", "token_count").toPandas()
#     fig = px.histogram(length_pd, x="token_count", nbins=50, color="token_count",
#                        title="Distribution of Token Counts per Document",
#                        labels={"token_count": "Number of Tokens"},
#                        color_discrete_sequence=["skyblue"])
#     fig.update_layout(xaxis_title="Number of Tokens", yaxis_title="Number of Documents", bargap=0.02, bargroupgap=0.1)
#     st.plotly_chart(fig)
# 
# def plot_top_tokens(spark_df):
#     tokenizer = RegexTokenizer(inputCol="text", outputCol="tokens")
#     tokenized_df = tokenizer.transform(spark_df)
#     tokens_df = (tokenized_df.select(explode(col("tokens")).alias("token"))
#                  .withColumn("token", trim(lower(col("token"))))
#                  .filter(length(col("token")) > 0))
#     token_counts = tokens_df.groupBy("token").count().orderBy(col("count").desc())
#     top20 = token_counts.limit(20).toPandas()
#     fig = px.bar(top20, x="token", y="count", text="count", title="Top 20 Words")
#     fig.update_traces(textposition="outside")
#     fig.update_layout(height=600, width=900, font=dict(family="Noto Sans Bengali, Arial Unicode MS, sans-serif", size=14))
#     return fig
# 
# def plot_category_distribution(spark_df):
#     category_distribution = spark_df.groupBy("category").count().toPandas()
#     fig = px.pie(category_distribution, names="category", values="count", title="Category Distribution", hole=0.3,
#                  color="category", color_discrete_sequence=px.colors.qualitative.Set1)
#     fig.update_traces(textinfo="percent+label", pull=[0.1, 0.1, 0.1])
#     st.plotly_chart(fig)
# 
# def plot_top_ngrams(spark_df, ngram_range=(2, 2), topN=20):
#     tokenizer = RegexTokenizer(inputCol="text", outputCol="tokens")
#     tokenized_df = tokenizer.transform(spark_df)
#     docs_pd = tokenized_df.select("tokens").toPandas()
#     docs_pd["joined"] = docs_pd["tokens"].apply(lambda x: " ".join(x))
#     vectorizer = CountVectorizer(ngram_range=ngram_range, max_features=topN)
#     X_ngram = vectorizer.fit_transform(docs_pd["joined"])
#     ngram_counts = X_ngram.toarray().sum(axis=0)
#     ngram_freq = pd.DataFrame({"ngram": vectorizer.get_feature_names_out(), "count": ngram_counts}).sort_values(by="count", ascending=False)
#     fig = px.bar(ngram_freq, x="ngram", y="count", text="count", title=f"Top {topN} N-grams")
#     fig.update_traces(textposition="outside")
#     st.plotly_chart(fig)
# 
# def plot_word_cloud(spark_df):
#     tokenizer = RegexTokenizer(inputCol="text", outputCol="tokens")
#     tokenized_df = tokenizer.transform(spark_df)
#     tokens_df = (tokenized_df.select(F.explode(F.col("tokens")).alias("token"))
#                  .withColumn("token", F.trim(F.lower(F.col("token"))))
#                  .filter(F.length(F.col("token")) > 0))
#     freq_df = tokens_df.groupBy("token").count().orderBy(F.desc("count"))
#     freq_pd = freq_df.toPandas()
#     freq_dict = dict(zip(freq_pd["token"], freq_pd["count"]))
#     font_candidates = ["/content/NotoSerifBengali-VariableFont_wdth,wght.ttf",
#                        "/content/NotoSansBengali-VariableFont_wdth,wght.ttf",
#                        "/content/Siyam Rupali Regular.ttf",
#                        "/content/NotoSansBengaliUI[wdth,wght].ttf"]
#     bangla_font = next((p for p in font_candidates if os.path.exists(p)), None)
#     wordcloud = WordCloud(font_path=bangla_font, width=1200, height=800, background_color="white", collocations=False).generate_from_frequencies(freq_dict)
#     plt.figure(figsize=(12, 8))
#     plt.imshow(wordcloud, interpolation="bilinear")
#     plt.axis("off")
#     plt.title("Word Cloud — Most Frequent Bangla Words", fontproperties=fm.FontProperties(fname=bangla_font), fontsize=18)
#     st.pyplot(plt)
# 
# # ===================== Sidebar Navigation =====================
# st.sidebar.title("Navigation")
# section = st.sidebar.radio(
#     "Choose a section:",
#     ["Dashboard", "Similarity Search", "Exploratory Data Analysis (EDA)", "Clustering"]
# )
# 
# # ===================== DASHBOARD =====================
# if section == "Dashboard":
#     st.title("📊 Overview Dashboard")
# 
#     # Load cleaned dataset again
#     csv_path = "/content/headlines.csv"
#     df = pd.read_csv(csv_path, encoding="utf-8")
#     df = df.rename(columns={"headline": "text", "newspaper name": "newspaper_name"})
#     df_filtered = df[df["category"].isin(["sports", "International", "politics"])]
# 
#     # Take random 5000 rows from each category
#     df_sports = df_filtered[df_filtered["category"] == "sports"].sample(n=5000, random_state=42)
#     df_international = df_filtered[df_filtered["category"] == "International"].sample(n=5000, random_state=42)
#     df_politics = df_filtered[df_filtered["category"] == "politics"].sample(n=5000, random_state=42)
# 
#     # Concatenate into final DataFrame
#     final_df = pd.concat([df_sports, df_international, df_politics], ignore_index=True)
# 
#     # Add doc_id
#     final_df["doc_id"] = final_df.index + 1
#     final_df = final_df[["doc_id", "text", "category", "newspaper_name"]]
# 
#     # Convert to Spark
#     spark_df = spark.createDataFrame(final_df)
# 
#     # ----------------- Basic Stats -----------------
#     total_documents = spark_df.count()
# 
#     # Vocabulary size
#     from pyspark.ml.feature import Tokenizer
#     tokenizer = Tokenizer(inputCol="text", outputCol="words")
#     words_data = tokenizer.transform(spark_df)
#     vocabulary_size = words_data.selectExpr("explode(words) as word").distinct().count()
# 
#     # Categories & Newspapers
#     num_categories = spark_df.select("category").distinct().count()
#     num_newspapers = spark_df.select("newspaper_name").distinct().count()
# 
#     # ----------------- Show Stats -----------------
#     col1, col2 = st.columns(2)
#     with col1:
#         st.metric("Total Documents", f"{total_documents:,}")
#         st.metric("Vocabulary Size", f"{vocabulary_size:,}")
#     with col2:
#         st.metric("Number of Categories", num_categories)
#         st.metric("Number of Newspapers", num_newspapers)
# 
#     # ----------------- Category Distribution -----------------
#     st.subheader("Category Distribution")
#     category_counts = final_df["category"].value_counts().reset_index()
#     category_counts.columns = ["Category", "Count"]
#     fig_cat = px.pie(category_counts, names="Category", values="Count", title="Documents per Category",
#                      color_discrete_sequence=px.colors.qualitative.Set2)
#     st.plotly_chart(fig_cat)
# 
#        # ----------------- Newspaper Distribution -----------------
#     st.subheader("Top Newspapers by Document Count")
#     newspaper_counts = final_df["newspaper_name"].value_counts().reset_index().head(15)
#     newspaper_counts.columns = ["Newspaper", "Count"]
#     fig_news = px.bar(newspaper_counts, x="Newspaper", y="Count", text="Count",
#                       title="Top 15 Newspapers")
#     fig_news.update_traces(textposition="outside")
#     st.plotly_chart(fig_news)
# 
# # ===================== SIMILARITY SEARCH =====================
# if section == "Similarity Search":
#     st.title("Find Nearest Neighbors for a Query")
#     query_selected = st.selectbox("Select a query:", [q[1] for q in sample_queries])
#     selected_query = next((item for item in sample_queries if item[1] == query_selected), None)
#     if selected_query:
#         query_doc_id, query_text = selected_query
#         query_row = query_feats.filter(query_feats["text"] == query_text).collect()[0]
#         nn_results = find_neighbors(query_row)
#         st.write(f"Top-5 nearest neighbors for query: **{query_text}**")
#         st.write(nn_results.toPandas())
# 
# # ===================== EDA =====================
# elif section == "Exploratory Data Analysis (EDA)":
#     st.header("Exploratory Data Analysis (EDA)")
#     df_eda = pd.read_csv("cleaned_headlines.csv")
#     spark_df = spark.createDataFrame(df_eda)
#     st.subheader("Token Count Distribution")
#     plot_token_count_distribution(spark_df)
#     st.subheader("Top 20 Words by Frequency")
#     st.plotly_chart(plot_top_tokens(spark_df))
#     st.subheader("Top 20 Bigrams (2-grams)")
#     bi_gram_fig = plot_top_ngrams(spark_df, ngram_range=(2, 2), topN=20)
#     if bi_gram_fig is not None:
#         st.plotly_chart(bi_gram_fig)
# 
#     st.subheader("Top 20 Trigrams (3-grams)")
#     tri_gram_fig = plot_top_ngrams(spark_df, ngram_range=(3, 3), topN=20)
#     if tri_gram_fig is not None:
#         st.plotly_chart(tri_gram_fig)
#     st.subheader("Category Distribution")
#     plot_category_distribution(spark_df)
#     st.subheader("Word Cloud — Most Frequent Bangla Words")
#     plot_word_cloud(spark_df)
# 
# # ===================== CLUSTERING =====================
# elif section == "Clustering":
#     st.title("Clustering with KMeans")
#     k_value = st.selectbox("Select the number of clusters (k):", [3, 5, 8], index=1)
#     df_clustered = load_clustered_data(k_value)
#     st.header("Clustering Results")
#     st.subheader(f"Data for k={k_value} Clusters")
#     st.write(df_clustered)
#     st.subheader(f"Cluster Size Distribution for k={k_value}")
#     plt.figure(figsize=(10, 6))
#     sns.countplot(x="cluster", data=df_clustered, palette="tab10")
#     plt.title(f"Cluster Size Distribution (k={k_value})")
#     st.pyplot(plt)
#     st.subheader(f"2D Scatter Plot of Clusters (k={k_value})")
#     fig, ax = plt.subplots(figsize=(10, 6))
#     sns.scatterplot(x="x", y="y", hue="cluster", data=df_clustered, palette="tab10", s=80, edgecolor="w", marker="o", ax=ax)
#     plt.title(f"2D Scatter Plot of Clusters (k={k_value})")
#     st.pyplot(fig)
# 
# if __name__ == "__main__":
#     st.write("Running the app. Use the sidebar to navigate between sections.")
#

from pyngrok import ngrok

# Set your ngrok authtoken here
ngrok.set_auth_token("32dXQgiv7eJoPES3FzcXJtXnyAh_56uqPFZqqB91qJRrsZPQD")

# Set up a tunnel for Streamlit
public_url = ngrok.connect('8501')
print('Streamlit app is live at:', public_url)

# Run the Streamlit app in the background
get_ipython().system('streamlit run appUp.py &')