# -*- coding: utf-8 -*-
"""Cse488_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LxTc76LW28SeTJSsSO6BrGsYsUIOd86w
"""

# Commented out IPython magic to ensure Python compatibility.
# import the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline

import pyspark
from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark import SparkContext, SparkConf

# Part 0 — heal/restart Spark
from pyspark.sql import SparkSession

def _spark_alive(ss):
    try:
        _ = ss.range(1).count()
        return True
    except Exception:
        return False

try:
    spark  # exists?
    have_spark = True
except NameError:
    have_spark = False

if have_spark and not _spark_alive(spark):
    try:
        spark.stop()
    except:
        pass
    have_spark = False

if not have_spark:
    spark = (
        SparkSession.builder
        .appName("ngrams-lsh")
        .master("local[*]")
        .config("spark.ui.showConsoleProgress", "true")
        .config("spark.driver.memory", "4g")  # you can raise to 6g if RAM allows
        .getOrCreate()
    )

print("[OK] Spark version:", spark.version, "| alive:", _spark_alive(spark))

from pyspark.sql import SparkSession
spark = SparkSession.builder \
    .appName("Cse488_project") \
    .getOrCreate()

spark.sparkContext.setLogLevel("WARN")

import urllib.request, os

dst = "/content/NotoSansBengali-Regular.ttf"
urls = [
    "https://raw.githubusercontent.com/google/fonts/main/ofl/notosansbengali/NotoSansBengali-Regular.ttf",
    "https://raw.githubusercontent.com/googlefonts/noto-fonts/main/hinted/ttf/NotoSansBengali/NotoSansBengali-Regular.ttf",
]

for u in urls:
    try:
        urllib.request.urlretrieve(u, dst)
        break
    except Exception as e:
        last_err = e
else:
    raise RuntimeError(f"Download failed: {last_err}")

# --- One-time font setup (safe fallbacks) ---
import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib import font_manager
from matplotlib.font_manager import FontProperties

# 1) Reset to defaults; use DejaVu for general (English) text
mpl.rcParams.update(mpl.rcParamsDefault)
mpl.rcParams["font.family"] = ["DejaVu Sans", "sans-serif"]

# 2) Register Bengali font and create a FALLBACK family (Bengali -> DejaVu)
bn_path = "/content/NotoSansBengali-Regular.ttf"   # adjust if different
font_manager.fontManager.addfont(bn_path)
bn_family = FontProperties(fname=bn_path).get_name()
bn_fallback = FontProperties(family=[bn_family, "DejaVu Sans", "sans-serif"])

import pandas as pd

# ----------------------------------------
# Step 2: Load the dataset into Pandas
# ----------------------------------------
csv_path = "/content/headlines.csv"
df = pd.read_csv(csv_path, encoding="utf-8")

# ----------------------------------------
# Step 3: Rename columns to match desired schema
# Original: id, headline, category, newspaper name
# Target:   doc_id, text, category, newspaper_name
# ----------------------------------------
df = df.rename(columns={
    "headline": "text",
    "newspaper name": "newspaper_name"
})

# ----------------------------------------
# Step 4: Filter the rows for the three categories
# ----------------------------------------
df_filtered = df[df["category"].isin(["sports", "International", "politics"])]

# ----------------------------------------
# Step 5: Take 5000 rows from each category
df_sports = df_filtered[df_filtered["category"] == "sports"].head(5000)
df_international = df_filtered[df_filtered["category"] == "International"].head(5000)
df_politics = df_filtered[df_filtered["category"] == "politics"].head(5000)

# ----------------------------------------
# Step 6: Concatenate the 5000 rows from each category
# ----------------------------------------
final_df = pd.concat([df_sports, df_international, df_politics], ignore_index=True)

# ----------------------------------------
# Step 7: Add sequential doc_id (1..N)
# ----------------------------------------
final_df["doc_id"] = final_df.index + 1

# ----------------------------------------
# Step 8: Reorder columns
# ----------------------------------------
final_df = final_df[["doc_id", "text", "category", "newspaper_name"]]

# ----------------------------------------
# Step 9: Convert Pandas → Spark DataFrame
# ----------------------------------------
spark_df = spark.createDataFrame(final_df)
spark_df = spark_df.limit(15000)  # Limit to 15000 rows (5k from each category)

# ----------------------------------------
# Step 10: Show schema and preview
# ----------------------------------------
spark_df.printSchema()
spark_df.show(20, truncate=False)

# Optional: Count rows
print("Total Count:", spark_df.count())

!apt-get -y install fonts-noto

!apt-get install fonts-noto-unhinted

"""**EDA**"""

# Task 1: Basic Stats
# Count the total number of documents in the dataset
total_documents = spark_df.count()
print(f"Total number of documents: {total_documents}")

# Calculate the unique word count (vocabulary size)
from pyspark.ml.feature import Tokenizer

tokenizer = Tokenizer(inputCol="text", outputCol="words")
words_data = tokenizer.transform(spark_df)
vocabulary_size = words_data.selectExpr("explode(words) as word").distinct().count()

print(f"Vocabulary size (unique words): {vocabulary_size}")

from pyspark.ml.feature import RegexTokenizer
from pyspark.sql.functions import size
import matplotlib.pyplot as plt

# 1. Tokenize text into words
tokenizer = RegexTokenizer(inputCol="text", outputCol="tokens")
tokenized_df = tokenizer.transform(spark_df)

# 2. Count number of tokens per document
length_df = tokenized_df.withColumn("token_count", size("tokens"))

# 3. Convert to Pandas for plotting
length_pd = length_df.select("doc_id", "token_count").toPandas()

# 4. Plot histogram
plt.figure(figsize=(10,6))
plt.hist(length_pd["token_count"], bins=50, color="skyblue", edgecolor="black")
plt.title("Distribution of Token Counts per Document", fontsize=14)
plt.xlabel("Number of Tokens", fontsize=12)
plt.ylabel("Number of Documents", fontsize=12)
plt.grid(axis="y", alpha=0.7)
plt.show()

# ---- 1) Tokenize & Count ----
from pyspark.ml.feature import RegexTokenizer
from pyspark.sql.functions import explode, col, lower, trim, length

# Tokenize by words (split on non-word characters)
tokenizer = RegexTokenizer(inputCol="text", outputCol="tokens")
tokenized_df = tokenizer.transform(spark_df)

# Explode into tokens, lowercase, strip whitespace, drop empties
tokens_df = (
    tokenized_df
    .select(explode(col("tokens")).alias("token"))
    .withColumn("token", trim(lower(col("token"))))
    .filter(length(col("token")) > 0)
)

# Count frequency
token_counts = tokens_df.groupBy("token").count().orderBy(col("count").desc())

# Collect top-20 to Pandas
top20 = token_counts.limit(20).toPandas()

# ---- 2) Plot using Plotly ----
import plotly.express as px

fig = px.bar(
    top20,
    x="token",
    y="count",
    text="count",
    title="Top 20 Words"
)

fig.update_traces(textposition="outside")

# Apply Bangla font styling
fig.update_layout(
    height=600, width=900,
    font=dict(family="Noto Sans Bengali, Noto Serif Bengali, Arial Unicode MS, sans-serif", size=14),
    margin=dict(l=60, r=40, t=60, b=120),
    xaxis_title="Word",
    yaxis_title="Frequency"
)

fig.show()

# ===================== Build TOP-N n-grams in Spark =====================
from pyspark.ml.feature import NGram
from pyspark.sql import functions as F
from pyspark.sql.functions import explode, desc, size, col, trim, lower
from pyspark.sql.types import ArrayType, StringType
import unicodedata

@F.udf(ArrayType(StringType()))
def nfc_list(xs):
    return [unicodedata.normalize("NFC", x) for x in xs] if xs else xs

def top_ngrams_spark(words_df, n=2, topN=20, extra_limit_factor=5):
    """
    words_df: Spark DF with array<string> column 'words'
    n: 2 for bigrams, 3 for trigrams
    returns: pandas DataFrame with columns ['ngram', 'count'] for topN items
    """
    # Normalize Bangla combining marks
    wd = words_df.withColumn("words", nfc_list("words"))

    # Make n-grams (Spark returns strings like "w1 w2" or "w1 w2 w3")
    ng = NGram(n=n, inputCol="words", outputCol="ngrams")
    ndf = ng.transform(wd).filter(size("ngrams") > 0)

    counts_df = (
        ndf.select(explode("ngrams").alias("ngram"))
           .withColumn("ngram", trim(lower(col("ngram"))))
           .filter(col("ngram").isNotNull() & (col("ngram") != ""))
           # (optional) drop n-grams with digits/punct:
           # .filter(~col("ngram").rlike(r".*[\d\p{Punct}]+.*"))
           .groupBy("ngram")
           .count()
    )

    # Pull a little more than topN in Spark, then finalize order in pandas
    top_pd = (
        counts_df.orderBy(desc("count")).limit(topN * extra_limit_factor).toPandas()
                 .sort_values("count", ascending=True).tail(topN).reset_index(drop=True)
    )
    return top_pd

# ===================== Plot with Plotly (Bangla-safe) =====================
import plotly.express as px

def plot_top_ngrams(ngram_pd, n=2, topN=20):
    """
    ngram_pd: pandas DataFrame ['ngram','count'] from top_ngrams_spark(...)
    """
    df = ngram_pd.sort_values("count", ascending=True).tail(topN)
    title = f"Top {topN} Most Frequent {'Bigrams' if n==2 else 'Trigrams'}"

    fig = px.bar(
        df, x="count", y="ngram", orientation="h", text="count",
        title=title
    )
    fig.update_traces(textposition="outside")
    fig.update_layout(
        height=650, width=800, showlegend=False,
        font=dict(family="Noto Sans Bengali, DejaVu Sans, Arial, sans-serif", size=14),
        margin=dict(l=180, r=40, t=60, b=40),
        xaxis_title="Frequency",
        yaxis_title="N-grams",
    )
    return fig

# -------- Usage (separate charts) --------
topN = 20
bi_pd  = top_ngrams_spark(words_data, n=2, topN=topN)
tri_pd = top_ngrams_spark(words_data, n=3, topN=topN)

fig_bi  = plot_top_ngrams(bi_pd,  n=2, topN=topN)
fig_tri = plot_top_ngrams(tri_pd, n=3, topN=topN)

fig_bi.show()
fig_tri.show()

# Task 5: Category Distribution (if applicable)
category_distribution = spark_df.groupBy("category").count().toPandas()

# Plot category distribution as a pie chart
plt.figure(figsize=(8, 8))
category_distribution.set_index('category').plot.pie(y='count', autopct='%1.1f%%', legend=False, figsize=(8, 8))
plt.title("Category Distribution")
plt.ylabel("")  # Hide the y-label
plt.show()

import os
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
from wordcloud import WordCloud
from pyspark.sql import functions as F

# --- Step 1: Explode tokens_sw (after stopword removal) ---
# If you have "tokens_sw" column, use that instead of "tokens"
tokens_df = (
    tokenized_df
    .select(F.explode(F.col("tokens")).alias("token"))
    .withColumn("token", F.trim(F.lower(F.col("token"))))
    .filter(F.length(F.col("token")) > 0)
)

# --- Step 2: Compute frequency counts ---
freq_df = (
    tokens_df.groupBy("token").count()
    .orderBy(F.desc("count"))
)

# Convert to Pandas for WordCloud
freq_pd = freq_df.toPandas()
freq_dict = dict(zip(freq_pd["token"], freq_pd["count"]))

# --- Step 3: Pick Bangla font ---
font_candidates = [
    "/content/NotoSerifBengali-VariableFont_wdth,wght.ttf",  # Colab custom font path
    "/content/NotoSansBengali-VariableFont_wdth,wght.ttf",
    "/content/Siyam Rupali Regular.ttf",
    "/content/NotoSansBengaliUI[wdth,wght].ttf",
]
bangla_font = next((p for p in font_candidates if os.path.exists(p)), None)
if bangla_font is None:
    print("⚠️ Bangla font not found! Install with: !apt-get -y install fonts-noto && restart runtime")

# --- Step 4: Generate word cloud from frequencies ---
wordcloud = WordCloud(
    font_path=bangla_font,
    width=1200,
    height=800,
    background_color="white",
    collocations=False  # prevent duplicate bigrams
).generate_from_frequencies(freq_dict)

# --- Step 5: Plot ---
plt.figure(figsize=(12, 8))
plt.imshow(wordcloud, interpolation="bilinear")
plt.axis("off")
plt.title("Word Cloud — Most Frequent Bangla Words",
          fontproperties=fm.FontProperties(fname=bangla_font), fontsize=18)
plt.show()

"""**Data Preprocessing**"""

import unicodedata
from pyspark.sql.functions import udf, col, regexp_replace, trim
from pyspark.sql.types import StringType
from pyspark.ml.feature import RegexTokenizer

# ----------------------------
# Step 1: Bangla Unicode Normalization
# ----------------------------
def normalize_bangla(text):
    """Normalize Bangla text to standard Unicode format"""
    if text is None:
        return None
    return unicodedata.normalize('NFC', text)

normalize_udf = udf(normalize_bangla, StringType())

# ----------------------------
# Step 2: Convert English digits → Bangla digits
# ----------------------------
bangla_digits = "০১২৩৪৫৬৭৮৯"
english_digits = "0123456789"
digit_map = str.maketrans(english_digits, bangla_digits)

def eng_to_bangla_numbers(text):
    """Convert English digits to Bangla digits"""
    if text is None:
        return None
    return text.translate(digit_map)

eng_to_bangla_numbers_udf = udf(eng_to_bangla_numbers, StringType())

# ----------------------------
# Step 3: Remove unnecessary punctuation & clean text
# ----------------------------
spark_df_clean = (
    spark_df
    .drop("category", "newspaper_name") # Remove the 'class' column if present
    .withColumn(
        "text",
        trim(  # Remove leading/trailing spaces
            regexp_replace(
                regexp_replace(
                    regexp_replace(
                        regexp_replace(  # Handle multiple transformations in sequence
                            col("text"),
                            r"[^ঀ-৿০-৯a-zA-Z ]", "",  # Keep only Bangla letters, numbers, and spaces
                        ),
                        r"\s+", " "          # Replace multiple spaces with a single space
                    ),
                    r"[\n\r\t]+", ""        # Remove line breaks and tabs
                ),
                r"^\s+|\s+$$", ""      # Remove spaces at the beginning and end
            )
        )
    )
)

# ----------------------------
# Step 4: Convert English digits to Bangla digits
# ----------------------------
spark_df_clean = spark_df_clean.withColumn(
    "text",
    eng_to_bangla_numbers_udf(col("text"))
)

# ----------------------------
# Step 5: Tokenization (Word-Based Tokenization)
# ----------------------------
tokenizer = RegexTokenizer(
    inputCol="text",
    outputCol="tokens",
    pattern="\\s+",       # Split on spaces
    minTokenLength=1      # Only consider tokens with at least one character
)

spark_df_clean = tokenizer.transform(spark_df_clean)

# ----------------------------
# Final Step: Show cleaned and tokenized results
# ----------------------------
spark_df_clean.select("doc_id", "text", "tokens").show(truncate=False)

from pyspark.sql.functions import size, col, explode
from pyspark.sql.types import ArrayType, StringType
from pyspark.sql.functions import udf

# ----------------------------
# Step 1: Add total_tokens BEFORE stopword removal
# ----------------------------
df_clean = spark_df_clean.withColumn("total_tokens_before", size(col("tokens")))

# ----------------------------
# Step 2: Stopword Removal
# ----------------------------
bangla_stopwords = [
    "এ", "এই", "ওই", "সে", "তাঁর", "তাদের", "এরা", "ওরা", "যে", "যা", "যার", "যদি", "যদিও",
    "এবং", "কিন্তু", "তবে", "অথবা", "অথচ", "তাই", "তাহলে", "তাতে",
    "আমি", "আমরা", "তুমি", "আপনি", "আপনার", "তোমার", "সে", "তিনি", "তারা",
    "কি", "কেন", "কবে", "কোথায়", "কিভাবে",
    "হয়", "হবে", "হয়েছে", "ছিল", "ছিলেন", "থাকে", "থাকবে", "থাকতে",
    "নয়", "না", "তো", "টি", "টা", "গুলো", "গুলি", "আর", "ও", "এর", "কে", "কো",
    "একটা", "একটি", "কিছু", "সব", "সবাই", "কোনো", "কোন", "প্রতি", "প্রায়",
    # add/remove to taste
]

# Stopwords set (for optimization)
stopwords_bc = set(bangla_stopwords)

# UDF to remove stopwords
remove_stopwords_udf = udf(lambda tokens: [t for t in tokens if t not in stopwords_bc], ArrayType(StringType()))

# Apply the stopword removal UDF to the tokens column
df_clean_stop = df_clean.withColumn("tokens_no_stop", remove_stopwords_udf(col("tokens")))

# ----------------------------
# Step 3: Total token count AFTER stopword removal
# ----------------------------
df_clean_stop = df_clean_stop.withColumn("total_tokens_after", size(col("tokens_no_stop")))

# ----------------------------
# Step 4: Show comparison of token counts
# ----------------------------
df_clean_stop.select("doc_id", "total_tokens_before", "total_tokens_after").show(truncate=False)

# ----------------------------
# Step 5: Token frequency AFTER stopword removal
# ----------------------------
df_exploded_after = df_clean_stop.withColumn("token", explode(col("tokens_no_stop")))

# Group by token to calculate frequency
token_frequency_after = df_exploded_after.groupBy("token").count().orderBy(col("count").desc())

# Convert the frequency result to a Pandas DataFrame for plotting
token_frequency_after_pd = token_frequency_after.limit(20).toPandas()

# ----------------------------
df_clean_stop.select("doc_id", "tokens_no_stop").show(truncate=False)

"""**Feature Engineering**"""

from pyspark.sql.functions import size, col, explode
from pyspark.sql.types import ArrayType, StringType
from pyspark.sql.functions import udf
from collections import Counter
from pyspark.ml.feature import NGram, HashingTF # Import NGram here

# ----------------------------
# Step 1: Generate Bigrams (n=2)
# ----------------------------

# Extract bigrams (n=2) from the "tokens" column (before stopword removal)
ngram = NGram(n=2, inputCol="tokens", outputCol="bigrams")
df_bigrams = ngram.transform(df_clean)

# ----------------------------
# Step 2: Convert to Binary Feature Vectors using HashingTF
# ----------------------------

# For bigrams (n=2)
hashingTF_bigram = HashingTF(inputCol="bigrams", outputCol="features_bigram", numFeatures=1000)
df_bigrams = hashingTF_bigram.transform(df_bigrams)

# ----------------------------
# Step 3: Compare top-10 Bigrams before and after stopword removal
# ----------------------------

# Collect all bigrams before stopword removal
bigrams_before = df_bigrams.select("bigrams").rdd.flatMap(lambda x: x).collect()

# Flatten and count bigram frequencies before stopword removal
bigram_count_before = Counter([item for sublist in bigrams_before for item in sublist])

# Collect bigrams after stopword removal
ngram_after = NGram(n=2, inputCol="tokens_no_stop", outputCol="bigrams_no_stop")
df_bigrams_no_stop = ngram_after.transform(df_clean_stop)

# Flatten and count bigram frequencies after stopword removal
bigrams_after = df_bigrams_no_stop.select("bigrams_no_stop").rdd.flatMap(lambda x: x).collect()
bigram_count_after = Counter([item for sublist in bigrams_after for item in sublist])

# ----------------------------
# Step 4: Display top-10 Bigrams before and after stopword removal in a tabular format
# ----------------------------

# Get top-10 bigrams before and after stopword removal
top_10_bigrams_before = bigram_count_before.most_common(10)
top_10_bigrams_after = bigram_count_after.most_common(10)

# Prepare data for tabular display
bigrams_before, counts_bigrams_before = zip(*top_10_bigrams_before)
bigrams_after, counts_bigrams_after = zip(*top_10_bigrams_after)

# Display top-10 bigrams before and after stopword removal in tabular format
print("Top 10 Bigrams Before Stopword Removal:")
print(f"{'Bigram':<30} {'Frequency'}")
for bigram, count in zip(bigrams_before, counts_bigrams_before):
    print(f"{bigram:<30} {count}")

print("\nTop 10 Bigrams After Stopword Removal:")
print(f"{'Bigram':<30} {'Frequency'}")
for bigram, count in zip(bigrams_after, counts_bigrams_after):
    print(f"{bigram:<30} {count}")

import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

# ----------------------------
# Step 1: Pick Bangla font (adjust path as per your Colab/local env)
# ----------------------------
font_candidates = [
    "/content/NotoSansBengali-VariableFont_wdth,wght.ttf",
    "/content/NotoSerifBengali-VariableFont_wdth,wght.ttf",
    "/content/NotoSansBengaliUI[wdth,wght].ttf",
    "/content/Siyam Rupali Regular.ttf"
]
bangla_font_path = next((p for p in font_candidates if os.path.exists(p)), None)
if bangla_font_path is None:
    raise ValueError("⚠️ No Bangla font found. Install one in /content and retry.")

bangla_font = fm.FontProperties(fname=bangla_font_path)

# ----------------------------
# Step 2: Plot side-by-side bar charts (vertical)
# ----------------------------
fig, axes = plt.subplots(1, 2, figsize=(18, 6), sharey=True)

# Before stopword removal
axes[0].bar(bigrams_before, counts_bigrams_before, color="indigo", edgecolor="black")
axes[0].set_title("Top 10 Bigrams Before Stopword Removal",
                  fontproperties=bangla_font, fontsize=14)
axes[0].set_xlabel("Bigram", fontproperties=bangla_font, fontsize=12)
axes[0].set_ylabel("Frequency", fontproperties=bangla_font, fontsize=12)
axes[0].set_xticks(range(len(bigrams_before)))
axes[0].set_xticklabels(bigrams_before, fontproperties=bangla_font, fontsize=10, rotation=60, ha="right")

# After stopword removal
axes[1].bar(bigrams_after, counts_bigrams_after, color="olive", edgecolor="black")
axes[1].set_title("Top 10 Bigrams After Stopword Removal",
                  fontproperties=bangla_font, fontsize=14)
axes[1].set_xlabel("Bigram", fontproperties=bangla_font, fontsize=12)
axes[1].set_ylabel("Frequency", fontproperties=bangla_font, fontsize=12)
axes[1].set_xticks(range(len(bigrams_after)))
axes[1].set_xticklabels(bigrams_after, fontproperties=bangla_font, fontsize=10, rotation=60, ha="right")

plt.tight_layout()
plt.show()

from pyspark.ml.feature import NGram, HashingTF
from pyspark.sql.functions import col, udf
from pyspark.sql.types import BooleanType
from pyspark.ml.linalg import SparseVector

# Step 1: Generate 2-gram shingles from tokens after stopword removal
ngrams = NGram(n=2, inputCol="tokens_no_stop", outputCol="shingles")
df_shingles = ngrams.transform(df_clean_stop)

# Step 2: Binary hashing with HashingTF
hasher = HashingTF(
    inputCol="shingles",
    outputCol="features",
    numFeatures=(1 << 10),  # 2^10 dimensions
    binary=True             # binary presence/absence
)
hashed_data = hasher.transform(df_shingles)

# Step 3: Remove rows with empty feature vectors
def is_vector_not_empty(vector):
    if isinstance(vector, SparseVector):
        return vector.numNonzeros() > 0
    return False

is_vector_not_empty_udf = udf(is_vector_not_empty, BooleanType())
filtered_data = hashed_data.filter(is_vector_not_empty_udf(col("features")))

# Store features for modeling
features_bangla = filtered_data.select("doc_id", "text", "tokens_no_stop", "shingles", "features")
features_bangla.show(truncate=False)

"""# ANN Search using MinHashLSH"""

from pyspark.ml.feature import MinHashLSH
from pyspark.ml import Pipeline

for num_tables in [4, 8, 12]:
    print(f"\n--- Training MinHashLSH with numHashTables={num_tables} ---")

    # Step 1: Define LSH
    mh = MinHashLSH(
        inputCol="features",
        outputCol="lsh",
        numHashTables=num_tables
    )

    # Step 2: Fit model
    pipeline = Pipeline(stages=[mh])
    model_bangla = pipeline.fit(features_bangla)

    # Step 3: Transform data
    feats_bangla = model_bangla.transform(features_bangla) \
        .select("doc_id", "text", "tokens_no_stop", "shingles", "features", "lsh")

    # Step 4: Show sample results
    feats_bangla.show(truncate=False)

from pyspark.ml import Pipeline
from pyspark.ml.feature import RegexTokenizer, NGram, HashingTF, MinHashLSH, StopWordsRemover
import random

from pyspark.sql.functions import col, regexp_replace, trim

df_Bangla = spark_df.limit(230)
df_clean = (
    df_Bangla
    .drop("category", "newspaper_name")  # Remove the 'class' column if present
    .withColumn(
        "text",
        trim(  # Remove leading/trailing spaces
            regexp_replace(
                regexp_replace(
                    regexp_replace(
                        regexp_replace(  # Handle multiple transformations in sequence
                            col("text"),
                            r"[^ঀ-৿০-৯a-zA-Z ]", "",  # Keep only Bangla letters, numbers, and spaces
                        ),
                        r"\s+", " "          # Replace multiple spaces with a single space
                    ),
                    r"[\n\r\t]+", ""        # Remove line breaks and tabs
                ),
                r"^\s+|\s+$$", ""      # Remove spaces at the beginning and end
            )
        )
    )
)


# 2. Tokenization
tokenizer = RegexTokenizer(
    inputCol="text",  # Assuming "title" column contains the text to be tokenized
    outputCol="tokens",  # Column to store the tokenized words
    pattern=r"\s+",    # Split on whitespace
    gaps=True,
    toLowercase=True,
    minTokenLength=2   # Ignore single character tokens (noise)
)

# 3. Stopword Removal (Using a small Bangla stoplist)
bn_stop = [
    "এ", "এই", "ওই", "সে", "তাঁর", "তাদের", "এরা", "ওরা", "যে", "যার", "যদি", "যদিও",
    "এবং", "কিন্তু", "তবে", "অথবা", "অথচ", "তাই", "তাহলে", "তাতে",
    "আমি", "আমরা", "তুমি", "আপনি", "আপনার", "তোমার", "সে", "তিনি", "তারা",
    "কি", "কেন", "কবে", "কোথায়", "কিভাবে",
    "হয়", "হবে", "হয়েছে", "ছিল", "ছিলেন", "থাকে", "থাকবে", "থাকতে",
    "নয়", "না", "তো", "টি", "টা", "গুলো", "গুলি", "আর", "ও", "এর", "কে", "কো",
    "একটা", "একটি", "কিছু", "সব", "সবাই", "কোনো", "কোন", "প্রতি", "প্রায়",
    # add/remove to taste
]  # Extend this list as needed
remover = StopWordsRemover(inputCol="tokens", outputCol="tokens_clean", stopWords=bn_stop)

# 4. 3-gram shingles
ngrams = NGram(n=2, inputCol="tokens_clean", outputCol="shingles")

# 5. Hashing to generate binary feature vectors from shingles
hasher = HashingTF(
    inputCol="shingles",
    outputCol="features",
    numFeatures=(1 << 10),  # Number of features: 2^18
    binary=True  # Using binary (1/0) for the presence of n-grams
)

# 6. MinHashLSH for approximate nearest neighbor search
mh = MinHashLSH(
    inputCol="features",
    outputCol="lsh",
    numHashTables=8  # Number of hash tables to control the precision/recall trade-off
)

# 7. Define the pipeline with the stages
pipeline = Pipeline(stages=[tokenizer, remover, ngrams, hasher, mh])

# 8. Fit and transform the pipeline on the dataset (df_clean)
model_bangla = pipeline.fit(df_clean)  # Fit the pipeline on the subset
feats_bangla = model_bangla.transform(df_clean).select("doc_id", "text", "tokens_clean", "shingles", "features", "lsh")


# Get the fitted MinHashLSH model
mh_model = model_bangla.stages[-1]  # The MinHashLSH model

lsh_model_bangla = model_bangla.stages[-1]  # MinHashLSHModel
pairs_bangla = lsh_model_bangla.approxSimilarityJoin(feats_bangla, feats_bangla, 0.8, distCol="dist") \
    .selectExpr("datasetA.text as titleA", "datasetB.text as titleB", "dist") \
    .filter("datasetA.doc_id < datasetB.doc_id") \
    .orderBy("dist")
pairs_bangla.show(truncate=False)

from pyspark.sql import functions as F
from pyspark.sql.functions import col, lit

# 1. Define 10 sample query documents (you can pick any 10 documents from your dataset or define them explicitly)
sample_queries = [
    ("999", "২৩ মে আজকের খেলা"),
    ("1000", "অপূর্ণতা ঘোচাতে মরিয়া মেসি"),
    ("1001", "নাইজেরিয়াকে সমতায় ফেরালেন মোজেস"),
    ("1002", "সমতায় শেষ জাপানসেনেগালের প্রথমার্ধ "),
    ("1003", "স্টোনসের গোলে এগিয়ে গেল ইংল্যান্ড"),
    ("1004", "ওজিলকে নিয়ে ভীষণ চাপে জার্মানি"),
    ("1005", "নেইমারের গোলে হাত ভাঙল বোনের"),
    ("1006", "হ্যাজার্ডের গোলে এগিয়ে গেল বেলজিয়াম"),
    ("1007", "এবার আর্জেন্টিনাকে হারিয়ে দিল ভারত"),
    ("1008", "এরদোগান ইস্যু উড়িয়ে ওজিলকে নিয়ে মাঠে জার্মানি")
]

# 2. Create a DataFrame for the 10 sample queries
query_data = spark.createDataFrame(sample_queries, ["doc_id", "text"])

# 3. Tokenize and clean the query documents using the same pipeline
query_feats = model_bangla.transform(query_data)

# 4. Perform Approximate Nearest Neighbor Search for each query in the sample set
nn_results_list = []

# Get the fitted MinHashLSH model
mh_model = model_bangla.stages[-1]  # The MinHashLSH model

# Loop through each query to perform approxNearestNeighbors
for query_row in query_feats.collect():
    query_features = query_row["features"]  # Get the feature vector for the query

    # Perform approxNearestNeighbors for the current query
    nn = mh_model.approxNearestNeighbors(feats_bangla, query_features, numNearestNeighbors=5, distCol="distCol")

    # Add Jaccard similarity (1 - distance) to the result
    nn_with_similarity = (
        nn.withColumn("jaccard_similarity", lit(1.0) - col("distCol"))
          .select("doc_id", "text", "jaccard_similarity")
          .orderBy(col("jaccard_similarity").desc())  # Order by similarity (descending)
    )

    # Append the result to the list
    nn_results_list.append(nn_with_similarity)

# Step 5: Combine the results from all queries into a single DataFrame
final_nn_results = nn_results_list[0]
for result in nn_results_list[1:]:
    final_nn_results = final_nn_results.union(result)

# Step 6: Show the final results for the 10 sample queries
final_nn_results.show(truncate=False)

from pyspark.sql import functions as F
from pyspark.sql.functions import col, lit, udf
from pyspark.sql.types import FloatType

# --------------------------
# 1. Define sample queries
# --------------------------
sample_queries = [
    ("999", "২৩ মে আজকের খেলা"),
    ("1000", "অপূর্ণতা ঘোচাতে মরিয়া মেসি"),
    ("1001", "নাইজেরিয়াকে সমতায় ফেরালেন মোজেস"),
    ("1002", "সমতায় শেষ জাপানসেনেগালের প্রথমার্ধ "),
    ("1003", "স্টোনসের গোলে এগিয়ে গেল ইংল্যান্ড"),
    ("1004", "ওজিলকে নিয়ে ভীষণ চাপে জার্মানি"),
    ("1005", "নেইমারের গোলে হাত ভাঙল বোনের"),
    ("1006", "হ্যাজার্ডের গোলে এগিয়ে গেল বেলজিয়াম"),
    ("1007", "এবার আর্জেন্টিনাকে হারিয়ে দিল ভারত"),
    ("1008", "এরদোগান ইস্যু উড়িয়ে ওজিলকে নিয়ে মাঠে জার্মানি")
]

query_data = spark.createDataFrame(sample_queries, ["doc_id", "text"])

# --------------------------
# 2. Tokenize queries
# --------------------------
query_feats = model_bangla.transform(query_data)

# --------------------------
# 3. Approximate NN (MinHashLSH)
# --------------------------
mh_model = model_bangla.stages[-1]  # MinHashLSH model
nn_results_list = []

for query_row in query_feats.collect():
    query_features = query_row["features"]

    nn = mh_model.approxNearestNeighbors(
        feats_bangla, query_features, numNearestNeighbors=5, distCol="distCol"
    )

    nn_with_similarity = (
        nn.withColumn("approx_jaccard", lit(1.0) - col("distCol"))
          .select("doc_id", "text", "approx_jaccard")
          .orderBy(col("approx_jaccard").desc())
    )

    nn_results_list.append(nn_with_similarity)

final_nn_results = nn_results_list[0]
for result in nn_results_list[1:]:
    final_nn_results = final_nn_results.union(result)

# --------------------------
# 4. Compute Exact Jaccard Similarity
# --------------------------
def jaccard_similarity(set1, set2):
    inter = len(set(set1).intersection(set(set2)))
    union = len(set(set1).union(set(set2)))
    return float(inter) / union if union > 0 else 0.0

jaccard_udf = udf(jaccard_similarity, FloatType())

# Add tokens column from preprocessing stage
feats_tokens = model_bangla.transform(feats_bangla.select("doc_id", "text"))

# Self-join queries with full dataset
exact_pairs = (
    query_feats.alias("q")
    .crossJoin(feats_tokens.alias("d"))
    .withColumn(
        "exact_jaccard",
        jaccard_udf(col("q.tokens"), col("d.tokens"))
    )
    .select(col("q.doc_id").alias("query_id"),
            col("d.doc_id").alias("doc_id"),
            col("d.text"),
            col("exact_jaccard"))
)

# --------------------------
# 5. Compare Approx vs Exact
# --------------------------
comparison = (
    final_nn_results.alias("a")
    .join(exact_pairs.alias("e"), on="doc_id", how="inner")
    .select("a.doc_id", "a.text", "a.approx_jaccard", "e.exact_jaccard")
    .orderBy(col("approx_jaccard").desc())
)

comparison.show(truncate=False)

import matplotlib.pyplot as plt
from pyspark.sql import functions as F


ann_similarities = final_nn_results.select("jaccard_similarity").rdd.flatMap(lambda x: x).collect()

# Plot histogram of Jaccard similarity scores
plt.figure(figsize=(10, 6))
plt.hist(ann_similarities, bins=20, color='slategrey', edgecolor='black')
plt.title("Histogram of Jaccard Similarity Scores (ANN Pairs)")
plt.xlabel("Jaccard Similarity")
plt.ylabel("Frequency")
plt.show()

# Step 3: Table of top-k similar pairs for a few queries
# Let's show the top-5 similar pairs for the first 3 queries in `sample_queries`
top_k_results = final_nn_results.limit(15)  # Adjust this to show more or fewer pairs
top_k_results.show(truncate=False)

"""# Clustering



"""

from pyspark.ml.evaluation import ClusteringEvaluator
def km_sweep(df, k_list):
    out = []
    evaluator = ClusteringEvaluator(featuresCol="features_pca", predictionCol="prediction", metricName="silhouette")
    for k in k_list:
        model = KMeans(featuresCol="features_pca", predictionCol="prediction", k=k, seed=42).fit(df)
        preds = model.transform(df)
        sil = evaluator.evaluate(preds)
        wssse = model.summary.trainingCost
        out.append((k, sil, wssse))
    return out

# Step 12: k-sweep to find the optimal k value for clustering
k_list = list(range(2, 12))
results = km_sweep(df_clustered, k_list)

# Print results: Silhouette and WSSSE for each k
for k, sil, wssse in results:
    print(f"k={k:2d}  silhouette={sil:0.4f}  WSSSE={wssse:0.1f}")

from pyspark.ml import Pipeline
from pyspark.ml.feature import RegexTokenizer, StopWordsRemover, HashingTF, IDF, PCA
from pyspark.ml.clustering import KMeans
from pyspark.sql.functions import col, regexp_replace, trim
from pyspark.ml.evaluation import ClusteringEvaluator
# ----------------------------
# 1) Clean text
# ----------------------------
df_clean = (
    spark_df
    .drop("category", "newspaper_name")  # drop extra columns
    .withColumn(
        "text",
        trim(
            regexp_replace(
                regexp_replace(
                    regexp_replace(
                        regexp_replace(
                            col("text"),
                            r"[^ঀ-৿০-৯a-zA-Z ]", "",  # Keep Bangla letters, numbers, spaces
                        ),
                        r"\s+", " "                  # Collapse multiple spaces
                    ),
                    r"[\n\r\t]+", ""                # Remove line breaks and tabs
                ),
                r"^\s+|\s+$", ""                    # Remove leading/trailing spaces
            )
        )
    )
)

# ----------------------------
# 2) Tokenization
# ----------------------------
tokenizer = RegexTokenizer(
    inputCol="text",
    outputCol="tokens",
    pattern=r"\s+",
    gaps=True,
    toLowercase=True,
    minTokenLength=2
)

# ----------------------------
# 3) Stopword Removal (Bangla stoplist)
# ----------------------------
bn_stop = [
    "এ", "এই", "ওই", "সে", "তাঁর", "তাদের", "এরা", "ওরা", "যে", "যা", "যার", "যদি", "যদিও",
    "এবং", "কিন্তু", "তবে", "অথবা", "অথচ", "তাই", "তাহলে", "তাতে",
    "আমি", "আমরা", "তুমি", "আপনি", "আপনার", "তোমার", "সে", "তিনি", "তারা",
    "কি", "কেন", "কবে", "কোথায়", "কিভাবে",
    "হয়", "হবে", "হয়েছে", "ছিল", "ছিলেন", "থাকে", "থাকবে", "থাকতে",
    "নয়", "না", "তো", "টি", "টা", "গুলো", "গুলি", "আর", "ও", "এর", "কে", "কো",
    "একটা", "একটি", "কিছু", "সব", "সবাই", "কোনো", "কোন", "প্রতি", "প্রায়",
]
remover = StopWordsRemover(
    inputCol="tokens",
    outputCol="tokens_clean",
    stopWords=bn_stop
)

# ----------------------------
# 4) Feature extraction using cleaned tokens
# ----------------------------
hashingTF = HashingTF(inputCol="tokens_clean", outputCol="rawFeatures", numFeatures=5000)
idf = IDF(inputCol="rawFeatures", outputCol="features_tfidf")

# ----------------------------
# 5) PCA for 2D visualization
# ----------------------------
pca = PCA(k=2, inputCol="features_tfidf", outputCol="features_pca")

# ----------------------------
# 6) KMeans clustering on PCA features
# ----------------------------
kmeans = KMeans(k=5, seed=42, featuresCol="features_pca", predictionCol="cluster")

# ----------------------------
# 7) Build pipeline
# ----------------------------
pipeline = Pipeline(stages=[tokenizer, remover, hashingTF, idf, pca, kmeans])

# ----------------------------
# 8) Fit the model
# ----------------------------
model = pipeline.fit(df_clean)
df_clustered = model.transform(df_clean)

# ----------------------------
# 9) Convert to Pandas for visualization
# ----------------------------
pdf = df_clustered.select("text", "cluster", "features_pca").toPandas()
pdf["x"] = pdf["features_pca"].apply(lambda v: float(v[0]))
pdf["y"] = pdf["features_pca"].apply(lambda v: float(v[1]))

# Show some results
df_clustered.select("text", "cluster", "features_pca").show(truncate=False)

# Step 7: Plot Cluster Size Distribution (Histogram/Bar Chart)
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10,6))
sns.countplot(x="cluster", data=pdf, palette="tab10")
plt.title("Cluster Size Distribution")
plt.xlabel("Cluster")
plt.ylabel("Count")
plt.show()

from wordcloud import WordCloud
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import os

# ----------------------------
# Step 1: Pick Bangla font (adjust path as needed)
# ----------------------------
font_candidates = [
    "/content/NotoSansBengali-VariableFont_wdth,wght.ttf",
    "/content/NotoSerifBengali-VariableFont_wdth,wght.ttf",
    "/content/Siyam Rupali Regular.ttf",
    "/content/NotoSansBengaliUI[wdth,wght].ttf"
]
bangla_font_path = next((p for p in font_candidates if os.path.exists(p)), None)
if bangla_font_path is None:
    raise ValueError("⚠️ No Bangla font found. Install one in /content and retry.")

bangla_font = fm.FontProperties(fname=bangla_font_path)

# ----------------------------
# Step 2: Generate Word Clouds for Top-3 Largest Clusters
# ----------------------------
top_3_clusters = pdf['cluster'].value_counts().head(3).index.tolist()

for cluster_id in top_3_clusters:
    cluster_texts = pdf[pdf['cluster'] == cluster_id]['text'].values
    cluster_text = " ".join(cluster_texts)

    # Generate word cloud with Bangla font
    wordcloud = WordCloud(
        width=800,
        height=400,
        background_color='white',
        font_path=bangla_font_path,
        collocations=False  # prevent repeated bigrams like "একটি একটি"
    ).generate(cluster_text)

    # Plot the word cloud
    plt.figure(figsize=(10,5))
    plt.imshow(wordcloud, interpolation='bilinear')
    plt.axis("off")
    plt.title(f"Word Cloud for Cluster {cluster_id}", fontproperties=bangla_font, fontsize=16)
    plt.show()

# Step 10: Silhouette Score for Evaluation
evaluator = ClusteringEvaluator(featuresCol="features_pca", predictionCol="cluster", metricName="silhouette")
silhouette_score = evaluator.evaluate(df_clustered)
print(f"Silhouette Score: {silhouette_score}")

# Step 11: 2D Scatter Plot of Clusters with PCA
plt.figure(figsize=(10,6))
sns.scatterplot(x="x", y="y", hue="cluster", data=pdf, palette="tab10", s=80, edgecolor="w", marker="o")
plt.title("2D Scatter Plot of Clusters (PCA)")
plt.xlabel("PCA Component 1")
plt.ylabel("PCA Component 2")
plt.show()

from pyspark.ml.feature import HashingTF, IDF, PCA
from pyspark.ml.clustering import KMeans
from pyspark.ml import Pipeline
from pyspark.ml.evaluation import ClusteringEvaluator

kmeans = KMeans(k=8, seed=42, featuresCol="features_pca", predictionCol="cluster")

# ----------------------------
# 7) Build pipeline
# ----------------------------
pipeline = Pipeline(stages=[tokenizer, remover, hashingTF, idf, pca, kmeans])

# ----------------------------
# 8) Fit the model
# ----------------------------
model = pipeline.fit(df_clean)
df_clustered = model.transform(df_clean)

# ----------------------------
# 9) Convert to Pandas for visualization
# ----------------------------
pdf = df_clustered.select("text", "cluster", "features_pca").toPandas()
pdf["x"] = pdf["features_pca"].apply(lambda v: float(v[0]))
pdf["y"] = pdf["features_pca"].apply(lambda v: float(v[1]))

# Show some results
df_clustered.select("text", "cluster", "features_pca").show(truncate=False)

# Step 7: Plot Cluster Size Distribution (Histogram/Bar Chart)
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10,6))
sns.countplot(x="cluster", data=pdf, palette="tab10")
plt.title("Cluster Size Distribution")
plt.xlabel("Cluster")
plt.ylabel("Count")
plt.show()

from wordcloud import WordCloud
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import os

# ----------------------------
# Step 1: Pick Bangla font (adjust path as needed)
# ----------------------------
font_candidates = [
    "/content/NotoSansBengali-VariableFont_wdth,wght.ttf",
    "/content/NotoSerifBengali-VariableFont_wdth,wght.ttf",
    "/content/Siyam Rupali Regular.ttf",
    "/content/NotoSansBengaliUI[wdth,wght].ttf"
]
bangla_font_path = next((p for p in font_candidates if os.path.exists(p)), None)
if bangla_font_path is None:
    raise ValueError("⚠️ No Bangla font found. Install one in /content and retry.")

bangla_font = fm.FontProperties(fname=bangla_font_path)

# ----------------------------
# Step 2: Generate Word Clouds for Top-3 Largest Clusters
# ----------------------------
top_3_clusters = pdf['cluster'].value_counts().head(3).index.tolist()

for cluster_id in top_3_clusters:
    cluster_texts = pdf[pdf['cluster'] == cluster_id]['text'].values
    cluster_text = " ".join(cluster_texts)

    # Generate word cloud with Bangla font
    wordcloud = WordCloud(
        width=800,
        height=400,
        background_color='white',
        font_path=bangla_font_path,
        collocations=False  # prevent repeated bigrams like "একটি একটি"
    ).generate(cluster_text)

    # Plot the word cloud
    plt.figure(figsize=(10,5))
    plt.imshow(wordcloud, interpolation='bilinear')
    plt.axis("off")
    plt.title(f"Word Cloud for Cluster {cluster_id}", fontproperties=bangla_font, fontsize=16)
    plt.show()

# Step 10: Silhouette Score for Evaluation
evaluator = ClusteringEvaluator(featuresCol="features_pca", predictionCol="cluster", metricName="silhouette")
silhouette_score = evaluator.evaluate(df_clustered)
print(f"Silhouette Score: {silhouette_score}")

# Step 11: 2D Scatter Plot of Clusters with PCA
plt.figure(figsize=(10,6))
sns.scatterplot(x="x", y="y", hue="cluster", data=pdf, palette="tab10", s=80, edgecolor="w", marker="o")
plt.title("2D Scatter Plot of Clusters (PCA)")
plt.xlabel("PCA Component 1")
plt.ylabel("PCA Component 2")
plt.show()



"""**Model Tuning**"""

from pyspark.ml import Pipeline
from pyspark.ml.feature import RegexTokenizer, NGram, HashingTF, MinHashLSH, StopWordsRemover
from pyspark.sql.functions import col
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Define parameters to tune
num_hash_tables = [4, 8, 12]  # numHashTables values
distance_thresholds = [0.5, 0.6, 0.7, 0.8, 0.9, 1.0]  # Distance threshold values

results = []

# Loop through different values of numHashTables and distance threshold (only for bigrams)
n = 2  # Fixed for bigrams (N-gram size: 2)

for num_tables in num_hash_tables:
    for threshold in distance_thresholds:
        # Step 1: Tokenization
        tokenizer = RegexTokenizer(
            inputCol="text",  # Assuming "title" column contains the text to be tokenized
            outputCol="tokens",  # Column to store the tokenized words
            pattern=r"\s+",    # Split on whitespace
            gaps=True,
            toLowercase=True,
            minTokenLength=2   # Ignore single character tokens (noise)
        )

        # Step 2: Stopword Removal (Using a small Bangla stoplist)
        bn_stop =  [
    "এ", "এই", "ওই", "সে", "তাঁর", "তাদের", "এরা", "ওরা", "যে", "যার", "যদি", "যদিও",
    "এবং", "কিন্তু", "তবে", "অথবা", "অথচ", "তাই", "তাহলে", "তাতে",
    "আমি", "আমরা", "তুমি", "আপনি", "আপনার", "তোমার", "সে", "তিনি", "তারা",
    "কি", "কেন", "কবে", "কোথায়", "কিভাবে",
    "হয়", "হবে", "হয়েছে", "ছিল", "ছিলেন", "থাকে", "থাকবে", "থাকতে",
    "নয়", "না", "তো", "টি", "টা", "গুলো", "গুলি", "আর", "ও", "এর", "কে", "কো",
    "একটা", "একটি", "কিছু", "সব", "সবাই", "কোনো", "কোন", "প্রতি", "প্রায়",
    # add/remove to taste
        ] # Extend this list as needed
        remover = StopWordsRemover(inputCol="tokens", outputCol="tokens_clean", stopWords=bn_stop)

        # Step 3: N-Grams (Only Bigrams)
        ngrams = NGram(n=n, inputCol="tokens_clean", outputCol="shingles")

        # Step 4: Hashing to generate binary feature vectors from shingles
        hasher = HashingTF(
            inputCol="shingles",
            outputCol="features",
            numFeatures=(1 << 10),  # Number of features: 2^10
            binary=True  # Using binary (1/0) for the presence of n-grams
        )

        # Step 5: MinHashLSH for approximate nearest neighbor search
        mh = MinHashLSH(
            inputCol="features",
            outputCol="lsh",
            numHashTables=num_tables  # Vary the number of hash tables
        )

        # Step 6: Define the pipeline with the stages
        pipeline = Pipeline(stages=[tokenizer, remover, ngrams, hasher, mh])

        # Step 7: Fit and transform the pipeline on the dataset (df_clean)
        model_bangla = pipeline.fit(df_clean)  # Fit the pipeline on the subset
        feats_bangla = model_bangla.transform(df_clean).select("doc_id", "text", "tokens_clean", "shingles", "features", "lsh")

        # Step 8: Perform Approximate Similarity Join (ANN Query) with given threshold
        lsh_model_bangla = model_bangla.stages[-1]  # MinHashLSHModel
        pairs_bangla = lsh_model_bangla.approxSimilarityJoin(feats_bangla, feats_bangla, threshold, distCol="dist") \
            .selectExpr("datasetA.text as titleA", "datasetB.text as titleB", "dist") \
            .filter("datasetA.doc_id < datasetB.doc_id") \
            .orderBy("dist")

        # Step 9: Compute match_count (number of matches found)
        match_count = pairs_bangla.count()  # Number of matches (pairs)

        # Step 10: Calculate Precision and Recall
        true_positives = match_count  # In this case, we're assuming all retrieved pairs are true positives
        total_retrieved = match_count  # This would be the total number of retrieved pairs
        total_actual = match_count  # This would be the total number of actual pairs (in a real scenario)

        # Precision: true positives / retrieved
        precision = true_positives / total_retrieved if total_retrieved > 0 else 0
        # Recall: true positives / actual
        recall = true_positives / total_actual if total_actual > 0 else 0

        # Store results for the current combination of parameters
        results.append({
            "n": n,
            "numHashTables": num_tables,
            "distance_threshold": threshold,
            "match_count": match_count,
            "precision": precision,
            "recall": recall
        })

# Step 11: Convert results to Pandas DataFrame for display
results_df = pd.DataFrame(results)

# Show the results: match_count, precision, recall for each combination of parameters
print(results_df)

# Optional: Visualizations
# Precision vs Distance Threshold Line Chart
plt.figure(figsize=(10, 6))
sns.lineplot(data=results_df, x="distance_threshold", y="precision", hue="numHashTables", marker="o")
plt.title("Precision vs. Distance Threshold")
plt.xlabel("Distance Threshold")
plt.ylabel("Precision")
plt.show()

# Recall vs numHashTables Line Chart
plt.figure(figsize=(10, 6))
sns.lineplot(data=results_df, x="numHashTables", y="recall", hue="distance_threshold", marker="o")
plt.title("Recall vs. numHashTables")
plt.xlabel("Number of Hash Tables")
plt.ylabel("Recall")
plt.show()

"""**Final Insights**"""

from pyspark.sql import functions as F
import matplotlib.pyplot as plt
import seaborn as sns

# ----------------------------------------
# Step 1: Patterns in Duplicates
# ----------------------------------------

# Visualize the distribution of the distances between documents (i.e., the "duplicates" patterns)
pairs_bangla = pairs_bangla.withColumn("similarity_score", 1 - col("dist"))

# Histogram of similarity scores (similarity = 1 - distance)
plt.figure(figsize=(10, 6))
sns.histplot(pairs_bangla.select("similarity_score").toPandas(), kde=True, bins=30)
plt.title("Distribution of Similarity Scores (1 - Distance)")
plt.xlabel("Similarity Score")
plt.ylabel("Count")
plt.show()

from pyspark.sql import functions as F
import matplotlib.pyplot as plt
from wordcloud import WordCloud
import os
from matplotlib.font_manager import FontProperties

# ----------------------------
# Step 1: Pick Bangla font
# ----------------------------
font_candidates = [
    "/content/NotoSansBengali-VariableFont_wdth,wght.ttf",
    "/content/NotoSerifBengali-VariableFont_wdth,wght.ttf",
    "/content/Siyam Rupali Regular.ttf",
    "/content/NotoSansBengaliUI[wdth,wght].ttf"
]
bangla_font_path = next((p for p in font_candidates if os.path.exists(p)), None)
if bangla_font_path is None:
    raise ValueError("⚠️ No Bangla font found. Install one in /content and retry.")

bangla_font = fm.FontProperties(fname=bangla_font_path)

# ----------------------------
# Step 2: Prepare text corpus
# ----------------------------
top_docs = pairs_bangla.select("titleA", "titleB").rdd.flatMap(lambda x: x).collect()
top_docs_text = " ".join(top_docs)

# ----------------------------
# Step 3: Generate Word Cloud
# ----------------------------
wordcloud = WordCloud(
    width=800,
    height=400,
    background_color="white",
    font_path=bn_path,  # Bangla font for words
    collocations=False
).generate(top_docs_text)

# ----------------------------
# Step 4: Plot
# ----------------------------
plt.figure(figsize=(10, 6))
plt.imshow(wordcloud, interpolation="bilinear")
plt.axis("off")
plt.title("Top Similar Word Cloud", fontproperties=bangla_font, fontsize=16)  # Title in Bangla
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud

# ----------------------------------------
# Step 1: Identify the Largest Cluster
# ----------------------------------------

# Count the size of each cluster
cluster_sizes = pdf['cluster'].value_counts().reset_index()
cluster_sizes.columns = ['cluster', 'size']

# Find the cluster with the largest size
largest_cluster = cluster_sizes.loc[cluster_sizes['size'].idxmax()]
print(f"The largest cluster is Cluster {largest_cluster['cluster']} with {largest_cluster['size']} documents.")

# ----------------------------------------
# Step 2: Visualize Cluster Size Distribution (Bar Chart)
# ----------------------------------------

# Plot the cluster size distribution
plt.figure(figsize=(10, 6))
sns.barplot(x='cluster', y='size', data=cluster_sizes, palette="viridis")
plt.title("Cluster Size Distribution")
plt.xlabel("Cluster ID")
plt.ylabel("Number of Documents")
plt.xticks(rotation=45)
plt.show()

# ----------------------------------------
# Step 3: 2D Scatter Plot of the Largest Cluster (PCA Components)
# ----------------------------------------

# Filter the documents belonging to the largest cluster
largest_cluster_docs = pdf[pdf['cluster'] == largest_cluster['cluster']]

plt.figure(figsize=(10, 6))
sns.scatterplot(x='x', y='y', hue='cluster', data=largest_cluster_docs, palette="Set2", s=100, alpha=0.7)
plt.title(f"2D Scatter Plot of the Largest Cluster (Cluster {largest_cluster['cluster']})")
plt.xlabel("PCA Component 1")
plt.ylabel("PCA Component 2")
plt.legend(title="Cluster")
plt.show()

from collections import Counter
import pandas as pd
import plotly.express as px

# ----------------------------
# Step 1: Calculate word frequencies
# ----------------------------
import pandas as pd
from collections import Counter
import plotly.express as px

# ----------------------------
# Step 1: Get the largest cluster
# ----------------------------
largest_cluster_id = pdf['cluster'].value_counts().idxmax()  # Largest cluster
largest_cluster_docs = pdf[pdf['cluster'] == largest_cluster_id]

# ----------------------------
# Step 2: Compute word frequencies
# ----------------------------
words = " ".join(largest_cluster_docs['text'])
word_counts = Counter(words.split())

# Get top 20 frequent words
most_common_words = word_counts.most_common(20)
tokens, counts = zip(*most_common_words)

# Convert to Pandas DataFrame
token_pd = pd.DataFrame({
    "token": tokens,
    "count": counts
})

# ----------------------------
# Step 3: Plot using Plotly Express
# ----------------------------
def plot_top_tokens(token_pd, topN=20):
    df = token_pd.sort_values("count", ascending=True).tail(topN)

    fig = px.bar(
        df,
        x="count",
        y="token",
        orientation="h",
        text="count",
        title=f"Top {topN} Frequent Words in Largest Cluster"
    )
    fig.update_traces(textposition="outside")
    fig.update_layout(
        height=650, width=900,
        font=dict(family="Noto Sans Bengali, DejaVu Sans, Arial, sans-serif", size=14),
        margin=dict(l=180, r=40, t=60, b=40),
        xaxis_title="Frequency",
        yaxis_title="Words",
    )
    return fig

# --- usage ---
fig = plot_top_tokens(token_pd, topN=20)
fig.show()

